spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

stripe:
  public:
    key: sk_test_51K6qpfGedVQTFauHtmMtmTcYDbQNISQKaDrotn1BgE0mgP8nVKaaAQp9EGGzjfzvgFw4KE6xbSIhJMON80ERBAfD00KxRJk6Kf